semi: false
tabWidth: 4
endOfLine: lf
useTabs: true
printWidth: 100
singleQuote: true
arrowParens: avoid
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
htmlWhitespaceSensitivity: ignore
